services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "cd ./app && python manage.py collectstatic --no-input --clear && gunicorn vintem_api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static_files
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static_files
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: