services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: >
        sh -c "
        python manage.py test
        && python manage.py createsuperuser --no-input
        && python manage.py runserver 0.0.0.0:8000
        "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - DJANGO_SUPERUSER_EMAIL=mlopes.matheus@gmail.com
    #   - DJANGO_SUPERUSER_USERNAME=admin
    #   - DJANGO_SUPERUSER_PASSWORD=mudar123
    depends_on:
      - db

  # createsuperuser:
  #   build: .
  #   command: && python manage.py createsuperuser --no-input
  #   environment:
  #     - DJANGO_SUPERUSER_EMAIL=mlopes.matheus@gmail.com
  #     - DJANGO_SUPERUSER_USERNAME=admin
  #     - DJANGO_SUPERUSER_PASSWORD=mudar123

volumes:
  postgres_data: