# Generated by Django 4.1.2 on 2022-10-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_created_at_remove_person_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
