# Generated by Django 4.1.2 on 2022-10-27 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=1, verbose_name='tipo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
