# Generated by Django 4.1.2 on 2022-10-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='kind',
            new_name='type',
        ),
    ]
