# Generated by Django 4.1.2 on 2022-10-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_kind_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('I', 'Income'), ('E', 'Expense')], max_length=1, null=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor'),
        ),
    ]
